package R6;

import j6.C1979n;

/* JADX INFO: loaded from: classes3.dex */
public interface a {

    /* JADX INFO: renamed from: R6.a$a, reason: collision with other inner class name */
    public static final class C0104a {
        public static Object[] a(a aVar, int i7) {
            throw new C1979n("Generated by Android Extensions automatically");
        }
    }
}
