###### Class eu.quitora.app.R is created by jadx
###### Class eu.quitora.app.R.anim is created by jadx
###### Class eu.quitora.app.R.animator is created by jadx
###### Class eu.quitora.app.R.array is created by jadx
###### Class eu.quitora.app.R.attr is created by jadx
###### Class eu.quitora.app.R.bool is created by jadx
###### Class eu.quitora.app.R.color is created by jadx
###### Class eu.quitora.app.R.dimen is created by jadx
###### Class eu.quitora.app.R.drawable is created by jadx
###### Class eu.quitora.app.R.font is created by jadx
###### Class eu.quitora.app.R.id is created by jadx
###### Class eu.quitora.app.R.integer is created by jadx
###### Class eu.quitora.app.R.interpolator is created by jadx
###### Class eu.quitora.app.R.layout is created by jadx
###### Class eu.quitora.app.R.mipmap is created by jadx
###### Class eu.quitora.app.R.plurals is created by jadx
###### Class eu.quitora.app.R.raw is created by jadx
###### Class eu.quitora.app.R.string is created by jadx
###### Class eu.quitora.app.R.style is created by jadx
###### Class eu.quitora.app.R.xml is created by jadx