package k4;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import l4.AbstractC2143e;
import p4.AbstractC2419b;

/* JADX INFO: renamed from: k4.f, reason: case insensitive filesystem */
/* JADX INFO: loaded from: classes.dex */
public abstract class AbstractC2025f {
    public static List a(String str) {
        int length = str.length();
        boolean z7 = false;
        AbstractC2419b.d(length >= 2, "Invalid path \"%s\"", str);
        if (length == 2) {
            if (str.charAt(0) == 1 && str.charAt(1) == 1) {
                z7 = true;
            }
            AbstractC2419b.d(z7, "Non-empty path \"%s\" had length 2", str);
            return Collections.EMPTY_LIST;
        }
        int length2 = str.length() - 2;
        ArrayList arrayList = new ArrayList();
        StringBuilder sb = new StringBuilder();
        int i7 = 0;
        while (i7 < length) {
            int iIndexOf = str.indexOf(1, i7);
            if (iIndexOf < 0 || iIndexOf > length2) {
                throw new IllegalArgumentException("Invalid encoded resource path: \"" + str + "\"");
            }
            int i8 = iIndexOf + 1;
            char cCharAt = str.charAt(i8);
            if (cCharAt == 1) {
                String strSubstring = str.substring(i7, iIndexOf);
                if (sb.length() != 0) {
                    sb.append(strSubstring);
                    strSubstring = sb.toString();
                    sb.setLength(0);
                }
                arrayList.add(strSubstring);
            } else if (cCharAt == 16) {
                sb.append(str.substring(i7, iIndexOf));
                sb.append((char) 0);
            } else {
                if (cCharAt != 17) {
                    throw new IllegalArgumentException("Invalid encoded resource path: \"" + str + "\"");
                }
                sb.append(str.substring(i7, i8));
            }
            i7 = iIndexOf + 2;
        }
        return arrayList;
    }

    public static l4.t b(String str) {
        return l4.t.u(a(str));
    }

    public static String c(AbstractC2143e abstractC2143e) {
        StringBuilder sb = new StringBuilder();
        int iQ = abstractC2143e.q();
        for (int i7 = 0; i7 < iQ; i7++) {
            if (sb.length() > 0) {
                e(sb);
            }
            d(abstractC2143e.m(i7), sb);
        }
        e(sb);
        return sb.toString();
    }

    public static void d(String str, StringBuilder sb) {
        int length = str.length();
        for (int i7 = 0; i7 < length; i7++) {
            char cCharAt = str.charAt(i7);
            if (cCharAt == 0) {
                sb.append((char) 1);
                sb.append((char) 16);
            } else if (cCharAt != 1) {
                sb.append(cCharAt);
            } else {
                sb.append((char) 1);
                sb.append((char) 17);
            }
        }
    }

    public static void e(StringBuilder sb) {
        sb.append((char) 1);
        sb.append((char) 1);
    }

    public static String f(String str) {
        StringBuilder sb = new StringBuilder(str);
        int length = sb.length() - 1;
        char cCharAt = sb.charAt(length);
        AbstractC2419b.d(cCharAt == 1, "successor may only operate on paths generated by encode", new Object[0]);
        sb.setCharAt(length, (char) (cCharAt + 1));
        return sb.toString();
    }
}
